/*
 * Author: tdanford
 * Date: Mar 23, 2009
 */
package edu.mit.csail.cgs.sigma.motifs;

import java.io.*;
import java.util.*;

import edu.mit.csail.cgs.utils.models.*;

/**
 * Input to this is generated by the main() method of MotifHitExpander.
 * @author tdanford
 *
 */
public class MotifHitLoader extends ModelInputIterator<MotifHit> {
	
	public MotifHitLoader(MotifProperties ps, String strain) throws IOException { 
		this(new File(ps.getMotifDirectory(), String.format("%s_motifs.txt", strain)));
	}
	
	public MotifHitLoader(File f) throws IOException { 
		super(new ModelInput.LineReader<MotifHit>(MotifHit.class, new FileReader(f)));
	}
}
